### ISSUE TITLE
Docker image label is incorrect

### ISSUE THREAD

**Issue by mook-as** [SUSE/kubecf-apps-dns#4]
Inspecting the image `ghcr.io/cfcontainerizationbot/kubecf-apps-dns:0.1.0`, I see that we have:

```yaml
            "Labels": {
                " org.opencontainers.image.description": "An image containing the KubeCF Apps DNS CoreDNS plugin",
                " org.opencontainers.image.title": "KubeCF Apps DNS",
                " org.opencontainers.image.url": "https://github.com/SUSE/kubecf-apps-dns",
                " org.opencontainers.image.vendor": "SUSE Cloud Application Platform",
                "org.opencontainers.image.created": "2020-09-11T07:39:34Z",
                "org.opencontainers.image.revision": "2175967e311c3ab8b4149129443caebda160374a",
                "org.opencontainers.image.source": "https://github.com/SUSE/kubecf-apps-dns",
                "org.opencontainers.image.version": "0.1.0"
            }
```

Notice that the first four labels have a space prefix in the key.
